server:
  port: 8080

spring:
  profiles:
    active: docker
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:auth_db}
      username: ${MONGO_USERNAME:auth_admin}
      password: ${MONGO_PASSWORD:auth_pass123}

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: false

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.microservices.auth: DEBUG
