spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/authdb}
  application:
    name: auth-service

user-service:
  url: ${USER_SERVICE_URL:http://user-service:8080}

jwt:
  secret: ${JWT_SECRET:yourSecretKey123!@#}
  expiration: ${JWT_EXPIRATION:86400000}
