server:
  port: ${SERVER_PORT:8080}  # Use environment variable, default to 8082

spring:
  profiles:
    active: docker
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:user_db}
      username: ${MONGO_USERNAME:user_admin}
      password: ${MONGO_PASSWORD:user_pass123}

logging:
  level:
    com.microservices.user: DEBUG

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
  servers:
    - url: /api/users
      description: User Service API
