server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: docker
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:users}
      username: ${MONGO_USERNAME:user_admin}
      password: ${MONGO_PASSWORD:user_pass123}
      authentication-database: admin
      auto-index-creation: true

# API Key configuration
app:
  api:
    key: ${API_KEY:microservice-api-key-2024}

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.microservices.user: DEBUG
    org.springframework.data.mongodb: DEBUG
