server:
  port: 8080

spring:
  profiles:
    active: docker
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:neo4j_pass123}
  
  # Disable Spring Security entirely for now
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

# OpenAPI Configuration - FORCE PUBLIC ACCESS
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  security:
    enabled: false

logging:
  level:
    com.microservices.note: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
