server:
  port: ${SERVER_PORT:8080}  # Changed from 8083 to 8080 to match docker-compose

spring:
  profiles:
    active: docker
  data:
    neo4j:
      uri: ${NEO4J_URI:bolt://localhost:7687}
      authentication:
        username: ${NEO4J_USERNAME:neo4j}
        password: ${NEO4J_PASSWORD:password}

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: false  # Disable built-in swagger UI since we use external one

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.microservices.note: DEBUG
