server:
  port: ${SERVER_PORT:8080}  # Changed from 8083 to 8080 to match docker-compose

spring:
  profiles:
    active: docker
  data:
    neo4j:
      uri: ${NEO4J_URI:bolt://localhost:7687}
      authentication:
        username: ${NEO4J_USERNAME:neo4j}
        password: ${NEO4J_PASSWORD:password}

logging:
  level:
    com.microservices.note: DEBUG
