server:
  port: 8080

spring:
  profiles:
    active: docker
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:neo4j_pass123}
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://keycloak:8080}/realms/${KEYCLOAK_REALM:microservices}
          jwk-set-uri: ${KEYCLOAK_URL:http://keycloak:8080}/realms/${KEYCLOAK_REALM:microservices}/protocol/openid-connect/certs

# OpenAPI Configuration - PUBLIC ACCESS
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.microservices.note: DEBUG
    org.springframework.security: DEBUG
    org.neo4j.driver: INFO
